name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Check the AWS Version
      run: |
        export AWS_ACCESS_KEY_ID=${{ secrets.username }}
        export AWS_SECRET_ACCESS_KEY=${{ secrets.password }}
        export AWS_DEFAULT_REGION=ap-south-1
        aws s3 cp . s3://findnumber/ --recursive --exclude="*."
        aws s3 ls
